server:
  port: 3333

spring:
  application:
    name: service-B

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
