server:
  port: 5555

spring:
  application:
    name: api-gateway

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
      path: /api-b/**
      serviceId: service-B


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000